# Configuration for installation on linux.  Will be sourced by
# sourcegit-start-linux.sh.

# On some installations it is necessary to prevent the use of an IM module
# (input method module).  If you can't input some diacritical marks (depending
# on keyboard layout that could be something like é, ñ, ä, ç, ø, or ğ) or use
# the compose character, you should try to set this variable to true.  You can
# test this in the search text box of SourceGit.
#
# prevent_im_module=false

# The scaling factor for SourceGit.  May be fractional (e.g. 1.25 or 0.75).
#
# scale_factor=1
